### ISSUE TITLE
Thiết kế database

### ISSUE THREAD

**Issue by phongle6893** [HCMUTE-ICT15-IOS-HCM17-05-G08/MockProject-funCINEMA#1]
Thiết kế database lưu trử:
- User
- Movie
- Cinema
- Booking
- Message

**Comment by nguyenvanphituoc** [comment]
Hoàn thành thiết kế cơ sở dữ liệu
![image](https://user-images.githubusercontent.com/22462183/26876308-cc6c2d4c-4baf-11e7-9f2a-6ad86594292a.png)
