### ISSUE TITLE
Fix Bug when clone project

### ISSUE THREAD

**Issue by nguyenvanphituoc** [HCMUTE-ICT15-IOS-HCM17-05-G08/MockProject-funCINEMA#15]
First clone project will compile error => missing GTMSessionFetcher or GoogleToolBoxForMac How to fix: Clone project and open this in terminal type: pod install => completed u will see the missing file under target folder rune compile again and go

**Comment by tiennth** [comment]
I think the cause of this error is you missed some file in your Pods project.
Maybe you forgot to add all the Pods-related files?
Here is the result after I run `pod install`, there are many untracked file means they were not added to your project before.
<img width="807" alt="screen shot 2017-06-10 at 3 03 52 pm" src="https://user-images.githubusercontent.com/3277692/27001198-3a3ffeee-4dee-11e7-9ad0-9a44468595fb.png">
